### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by OluOrojo** [alistairewj/challenge2012#2]
Hi, thanks for your code, how do we deal with incorrect values for the other variables not dealt with in the code e.g Albumin, BUN?

**Comment by alistairewj** [comment]
You could do any number of things; mean impute, median impute, normal impute, dummy variables, MICE, etc. All of them have drawbacks.

**Comment by OluOrojo** [comment]
Alright, thank you and where can I get reference ranges for the variables?

**Comment by alistairewj** [comment]
They're not available unfortunately.

**Comment by OluOrojo** [comment]
Hi,

In this git repository: https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3benchmark/resources/variable_ranges.csv

I found ranges I can use for my outlier handling, would you recommend combining these with those in your repository or using either or? Also do the ranges appear plausible to you? I am also using you thesis to identify how to transform the variables, I ask these questions as I am training a recurrent neural network to learn the icu outcomes however learning is not occurring I think the preprocessing and transformation of the variables is affecting the learning? Do you have any suggestions on how to encourage learning ?

**Comment by alistairewj** [comment]
The ranges seem reasonable. For training, I've seen target replication used to help a bit.

**Comment by OluOrojo** [comment]
Alright many thanks.
